[project]
name = "notion-game-list"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.3",
    "python-dotenv>=1.0.0",
    "requests>=2.3.0",
    "termcolor>=1.1.0",
]
